print("Hello World!")
print("Hello Again!")
print("I like typing this.")
print("This is fun.")
print('Yay! PRinting.')
print('I "said" do not touch this.')
print("I'd much rather you 'not'.")
print("This is the other line you wanted me to print, ya'll.")
#print("Commented out a line")
